### ISSUE TITLE
Wrong area target to insert htmlcode

### ISSUE THREAD

**Issue by moodleulpgc** [jmulet/moodle-tiny_codepro#10]
When a page display several HTML areas, and the user edits content with source code pro in the popup  the new content is not inserted in the area where source code tool has been invoked. 

Once one area in edited, then edition of the **other** areas will insert the content into the first one edited **NOT** into the area where tool is invoked. This result in content moving to other areas in the same page, and overwriting (and losing) the edited content. 

Working with moodle 4.4 and 4.5 dev

**Comment by jmulet** [comment]
Hi @moodleulpgc,

Thank you very much for reporting this issue, and I apologize for any inconvenience it may have caused. I have identified the problem and have addressed it in the latest update. The fix is included in the current version 1.1.2 (2024082502). The plugin has been tested up to Moodle 4.4.

If you encounter any further problems or have any other feedback, please don't hesitate to comment.

Best wishes,
Josep
